blank_issues_enabled: false
contact_links:
  - name: 🚀 Blockfield Launcher
    url: https://github.com/Blockfield/Blockfield-Launcher/releases/latest
    about: Проблемы самого лаунчера и загрузка последней версии
